# Generated by Django 5.0.6 on 2024-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('membership_type', models.CharField(choices=[('Ordinary', 'Ordinary Membership'), ('Premium', 'Premium Membership'), ('Vip', 'VIP Membership'), ('Gold', 'Gold Membership')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('year_at_panyango', models.CharField(max_length=9)),
                ('occupation', models.CharField(max_length=100)),
                ('membership_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='register_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('month_created', models.PositiveIntegerField(editable=False)),
                ('year_created', models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
