# Generated by Django 5.0.6 on 2024-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
